menu:
  - category: "Desarrollo"
    screen: "modules.development.main"
    icon: "icons/analysis_icon.png"
  - category: "Carga"
    screen: "modules.load.main"
    icon: "icons/execution_icon.png"
  - category: "Validaciones"
    screen: "modules.validation.main"
    icon: "icons/visor_icon.png"
  - category: "Extractores"
    screen: "modules.extraction.main"
    icon: "icons/visor_icon.png"
  - category: "Control-M"
    screen: "modules.controlm.main"
    icon: "icons/table_icon.png"
