menu:
  - category: "Inicio"
    screen: "main"
    icon: "icons/analysis_icon.png"
  - category: "Configuración"
    screen: "screens.execution"
    icon: "icons/execution_icon.png"
  - category: "Reportes"
    screen: "screens.viewer"
    icon: "icons/visor_icon.png"
  - category: "Ayuda"
    screen: "screens.viewer"
    icon: "icons/visor_icon.png"
  - category: "Salir"
    screen: "screens.table"
    icon: "icons/table_icon.png"
